baseURL = 'https://svin24.github.io/'
languageCode = 'en-us'
title = 'SViN Web'
theme = "digital-garden-hugo-theme"
canonifyURLs = true
publishDir = "docs"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 3

  [[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com/DrawingSViN'
  weight = 1

  [[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/SViN24'
  weight = 1

  [[menu.social]]
  name = 'Instagram'
  url = 'https://www.instagram.com/svinny24/'
  weight = 1